# -*- coding: utf-8 -*-
"""InventoryPredictionV0(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD7IXsq6Y10q9Cms6A329IAP6AE_Q_tE
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg") 
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import streamlit as st
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_absolute_percentage_error,mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error
import math
import xgboost as xgb
import lightgbm as lgb

df = pd.read_csv("D:\\Priceoye\\Inventory_Accuracy_ModelV1\\sales_inventory.csv")

# print(df["date"].dtype)

df["date"] = pd.to_datetime(df["date"])

df = df.sort_values(["sku_id","date"]).reset_index(drop=True)

df = (
    df.groupby(["sku_id", "date"], as_index=False)
      .agg({
          "brand": "first",
          "units_sold": "sum",
          "restocked_units": "sum",
          "recorded_stock": "last",
          "price": "mean"
      })
)

"""Adding Promotional flags"""

#adding promotional flags
#2026-02-09, 2026-04-13, 2026-06-15
#promotion till next week on each phone
df["promotional_flag_discount"] = 0

mask = (df["date"] >= "2026-02-09") & (df["date"] <= "2026-02-15")
mask2 = (df["date"] >= "2026-04-13") & (df["date"] <= "2026-04-20")
mask3 = (df["date"] >= "2026-06-15") & (df["date"] <= "2026-06-22")


df.loc[mask, "promotional_flag_discount"] = 5000
df.loc[mask2, "promotional_flag_discount"] = 3000
df.loc[mask3, "promotional_flag_discount"] = 4000

df.loc[df["date"] == "2026-04-13"]

df["net_price"] = df["price"] - df["promotional_flag_discount"]

df.head()

df.info()

weekly_df = (
    df.groupby(["sku_id", pd.Grouper(key="date", freq="W-MON")])
    .agg({
        'units_sold': 'sum',              # Total weekly demand
        'recorded_stock': 'last',         # Stock status at end of week
        'net_price': 'mean'                   # Average weekly price
    }))

weekly_df.describe()

a=0
for i in weekly_df.index.get_level_values("sku_id").unique():
  a +=1
  if a < 10:
    plt.figure(figsize=(10,5))
    plt.plot(weekly_df.loc[i]["units_sold"])
    plt.xlabel("Date")
    plt.ylabel("Units Sold")
    plt.title(f"Weekly Units Sold for {i}")
    plt.show()

weekly_df.loc[weekly_df.index.get_level_values('sku_id') == "SKU_INFINIX_0001"]

weekly_df['lag_1_week'] = weekly_df.groupby('sku_id')['units_sold'].shift(1)
weekly_df['lag_2_week'] = weekly_df.groupby('sku_id')['units_sold'].shift(2)
weekly_df['lag_4_week'] = weekly_df.groupby('sku_id')['units_sold'].shift(4)

weekly_df.head(10)

weekly_df.columns

weekly_df["rolling_4w_mean"] = (
    weekly_df.groupby("sku_id")["units_sold"]
    .transform(lambda x: x.shift(1).rolling(window=4, min_periods=1).mean())
)
weekly_df["rolling_4w_std"] = (
    weekly_df.groupby("sku_id")["units_sold"]
    .transform(lambda x: x.shift(1).rolling(window=4, min_periods=1).std())
)
weekly_df["rolling_4w_median"] = (
    weekly_df.groupby("sku_id")["units_sold"]
    .transform(lambda x: x.shift(1).rolling(window=4, min_periods=1).median())
)
weekly_df["rolling_8w_mean"] = (
    weekly_df.groupby("sku_id")["units_sold"]
    .transform(lambda x: x.shift(1).rolling(window=8, min_periods=1).mean())
)
weekly_df["rolling_8w_std"] = (
    weekly_df.groupby("sku_id")["units_sold"]
    .transform(lambda x: x.shift(1).rolling(window=8, min_periods=1).std())
)
# weekly_df["rolling_12w_mean"] = (
#     weekly_df.groupby("sku_id")["units_sold"]
#     .transform(lambda x: x.shift(1).rolling(window=12, min_periods=1).mean())
# )
#Removing it since it made the lgbm regressor worse

weekly_df.isna().sum()

weekly_df.loc[weekly_df.index.get_level_values("sku_id") == "SKU_APPLE_0002"]

weekly_df.dropna(inplace=True)

# print("Calculating the Metrics without losing outliers")
# R2 = r2_score(y_test,preds)# mape = mean_absolute_percentage_error(y_test,preds)
# wmape = mean_absolute_percentage_error(y_test,preds,sample_weight = y_test)
# print(f"R2 score: {R2}")
# print(f"WMAPE: {wmape * 100:.2f}%")
# print(f"MAPE: {mape * 100:.2f}%")

weekly_df.head()

sns.heatmap(weekly_df.corr(), annot=True, cmap='coolwarm')
plt.show()

df.head()

def checkLowSellingSKU():
  lowestUnitsSold = df.groupby("sku_id")["units_sold"].sum()
  underperforming_skus = lowestUnitsSold[lowestUnitsSold < lowestUnitsSold.sum().mean()].sort_values(ascending=True)

  return underperforming_skus

checkLowSellingSKU()

skuNunitsSold = checkLowSellingSKU()
plt.figure(figsize=(12, 6))
plt.scatter(range(len(skuNunitsSold)), skuNunitsSold.values)
plt.xlabel("SKU (index)")
plt.ylabel("Units Sold")
plt.title("SKU vs Units Sold")
plt.tight_layout()
plt.show()

def find_iqr_outliers(df):
    # Aggregate total sales per SKU
    sku_sales = df.groupby("sku_id")["units_sold"].sum()

    Q1 = sku_sales.quantile(0.25)
    Q3 = sku_sales.quantile(0.75)
    IQR = Q3 - Q1

    # Define thresholds
    upper_bound = Q3 + 1.5 * IQR
    lower_bound = Q1 - 1.5 * IQR

    # Extract outliers
    high_outliers = sku_sales[sku_sales > upper_bound]
    low_outliers = sku_sales[sku_sales < lower_bound]

    # print(f"Upper Bound: {upper_bound:.2f}")
    # print(f"High-Volume Outliers: {len(high_outliers)} SKUs")
    # print(f"Low-Volume Outliers: {len(low_outliers)} SKUs")

    return high_outliers, low_outliers

high_out, low_out = find_iqr_outliers(df)
print(f"{high_out} \n {low_out}")
high_out.to_csv("D:\\Priceoye\\Inventory_Accuracy_ModelV1\\high_volume_sellers.csv", index=True)

outliers = checkLowSellingSKU()

plt.figure(figsize=(8, 5))
plt.boxplot(outliers)
plt.title("Boxplot of Units Sold per SKU (Outliers as Dots)")
plt.ylabel("Total Units Sold")
plt.show()

def drawPlot(skuid, df):
    # 1. Filter for the specific SKU
    # Works whether sku_id is in a MultiIndex or a regular column
    if "sku_id" in df.index.names:
        subdf = df.xs(skuid, level="sku_id")
    else:
        subdf = df[df["sku_id"] == skuid]

    # Sort chronologically
    subdf = subdf.sort_values("date") if "date" in subdf.columns else subdf.sort_index()

    # 2. Extract x and y series directly from the filtered sub-dataframe
    x_dates = subdf["date"] if "date" in subdf.columns else subdf.index.get_level_values("date")
    y_sales = subdf["units_sold"]

    # 3. Render plot
    plt.figure(figsize=(10, 4))
    plt.plot(x_dates, y_sales, color="blue", marker="o", linewidth=2, label="Actual Demand")

    plt.title(f"Weekly Units Sold — {skuid}", fontsize=12, fontweight="bold")
    plt.xlabel("Date", fontsize=10)
    plt.ylabel("Units Sold", fontsize=10)
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# Call the function
drawPlot("SKU_INFINIX_0014", weekly_df)

# print(weekly_df.index.get_level_values("sku_id").unique())

weeklytraintest = weekly_df.copy()
weeklytraintest.reset_index(inplace=True)
X = weeklytraintest.drop(columns=["units_sold"])
y = weeklytraintest["units_sold"]

weeklytraintest = weeklytraintest.sort_values(["sku_id", "date"]).reset_index(drop=True)

def split_sku_data(group, train_pct=0.8):
    n_rows = len(group)
    train_size = int(n_rows * train_pct)

    # Assign split labels
    group["split"] = "train"
    group.iloc[train_size:, group.columns.get_loc("split")] = "test"
    return group

weeklytraintest = weeklytraintest.sort_values(["sku_id", "date"]).reset_index(drop=True)

# Position of each row within its SKU group (0, 1, 2, ...)
row_position = weeklytraintest.groupby("sku_id").cumcount()
# Total rows in each SKU group
group_size = weeklytraintest.groupby("sku_id")["sku_id"].transform("count")

train_cutoff = (group_size * 0.8).astype(int)

weeklytraintest["split"] = "train"
weeklytraintest.loc[row_position >= train_cutoff, "split"] = "test"

weeklytraintest_split = weeklytraintest

train_df = weeklytraintest_split[weeklytraintest_split['split'] == 'train'].drop(columns=['split'])
test_df = weeklytraintest_split[weeklytraintest_split['split'] == 'test'].drop(columns=['split'])
# print(f"Total Unique SKUs in Train: {train_df['sku_id'].nunique()}")
# print(f"Total Unique SKUs in Test : {test_df['sku_id'].nunique()}")

y_true = test_df["units_sold"]

predictions = {
    "Lag 1 Week": test_df["lag_1_week"],
    "Lag 4 Week": test_df["lag_4_week"],
    "Rolling 4W Mean": test_df["rolling_4w_mean"],
    "Rolling 4W Median": test_df["rolling_4w_median"],
    "Rolling 8W Mean": test_df["rolling_8w_mean"]
}

results = {}

for name, y_pred in predictions.items():
    mae = mean_absolute_error(y_true, y_pred)
    wmape = (abs(y_true - y_pred).sum() / abs(y_true).sum()) * 100
    results[name] = {
        "MAE": mae,
        "WMAPE": wmape
    }

    # print(f"{name}")
    # print(f"MAE : {mae} units away from actual")
    # print(f"WMAPE: {wmape:.2f}%\n")
# print(test_df.head())
def plotNaive(skuid):
    plt.figure(figsize=(12,5))

    sku_test_df = test_df[test_df["sku_id"] == skuid]

    plt.plot(sku_test_df["date"], sku_test_df["units_sold"], label="Actual")
    plt.plot(sku_test_df["date"], sku_test_df["lag_1_week"], label="Lag-1 Prediction")
    plt.plot(sku_test_df["date"], sku_test_df["rolling_4w_mean"], label="Rolling-4w-mean Prediction")
    plt.plot(sku_test_df["date"], sku_test_df["rolling_4w_median"], label="Rolling-4w-median Prediction")
    plt.plot(sku_test_df["date"], sku_test_df["lag_4_week"], label="Lag-4w Prediction")
    plt.plot(sku_test_df["date"], sku_test_df["rolling_8w_mean"], label="Rolling-8w-mean Prediction")
    # plt.plot(sku_test_df["date"], sku_test_df["rolling_12w_mean"], label="Rolling-12w-mean Prediction")
    # removing 12 week since it has made lgbm wors



    plt.legend()
    plt.xlabel("Date")
    plt.ylabel("Units Sold")
    plt.title(f"Naive Baseline for SKU: {skuid}")
    plt.show()

plotNaive("SKU_INFINIX_0004")

"""#Phase 4

##Training Model
"""

#Training the xgboost and lightgbm on this since it contains the splits

weeklytraintest_split.head()

train_df.head(20) #the train split
test_df.head(9) #the test split
# y_true #the units sold in test_df
# y_pred #old prediction by naive baseline

"""##Feature Selection"""

train_df["sku_id"] = train_df["sku_id"].astype("category")
test_df["sku_id"] = test_df["sku_id"].astype("category")

features = [
    "sku_id",
    "price",
    "recorded_stock",
    "day",
    "month"
]

train_df["day"] = train_df["date"].dt.day
train_df["month"] = train_df["date"].dt.month
train_df["year"] = train_df["date"].dt.year
# train_df["week_of_year"] = train_df["date"].dt.isocalendar().week.astype(int)

test_df["day"] = test_df["date"].dt.day
test_df["month"] = test_df["date"].dt.month
test_df["year"] = test_df["date"].dt.year
# test_df["week_of_year"] = test_df["date"].dt.isocalendar().week.astype(int)

target = "units_sold"
X_train = train_df.drop(columns = ["units_sold", "date"])
X_test = test_df.drop(columns = ["units_sold", "date"])

y_train = train_df["units_sold"]
y_test = test_df["units_sold"]

lgbm = lgb.LGBMRegressor(
    learning_rate=0.05,
    n_estimators=300,
    num_leaves=31,
    random_state=42
)

lgbm.fit(
    X_train,
    y_train,
    categorical_feature=["sku_id"]
)
pred = lgbm.predict(X_test)

mae = mean_absolute_error(y_test, pred)
wmape = (abs(y_test - pred).sum() / abs(y_test).sum()) * 100

# print("\nLightGBM Regression")
# print(f"MAE : {mae:.2f} units away from actual")
# print(f"WMAPE: {wmape:.2f}%\n")

y_test.head()

weekly_df.corr(numeric_only=True)["units_sold"].sort_values(ascending=False)

# print(df.shape)
# print(weekly_df.shape)
# print(weekly_df.groupby("sku_id").size().describe())

X_train.head()

X_train.head()

model = LinearRegression()
model.fit(X_train[["rolling_8w_mean"]], y_train)

pred2 = model.predict(X_test[["rolling_8w_mean"]])

maelr = mean_absolute_error(y_test, pred2)
# wmapelr = (abs(y_test - pred).sum() / abs(y_test).sum()) * 1
# print("\nLinear Regression")
# print(f"MAE : {maelr:.2f} units away from actual")
# print(f"WMAPE: {wmapelr:.2f}%\n"

plt.scatter(
    train_df["rolling_8w_mean"],
    y_train,
    alpha=0.3
)
plt.show()

test_df = test_df.copy()
test_df["lgbm_pred"] = pred
def plotLGB(skuid):
    sku_test_df = test_df[test_df["sku_id"] == skuid].sort_values("date")

    plt.figure(figsize=(12, 5))

    plt.plot(
        sku_test_df["date"],
        sku_test_df["units_sold"],
        marker="o",
        label="Actual"
    )

    plt.plot(
        sku_test_df["date"],
        sku_test_df["lgbm_pred"],
        marker="o",
        label="LightGBM"
    )

    plt.plot(
        sku_test_df["date"],
        sku_test_df["rolling_8w_mean"],
        marker="o",
        label="Rolling 8W Mean"
    )

    plt.title(f"Forecast Comparison - {skuid}")
    plt.xlabel("Date")
    plt.ylabel("Units Sold")
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()

for skuid in pd.read_csv("D:\\Priceoye\\Inventory_Accuracy_ModelV1\\high_volume_sellers.csv")["sku_id"]:
    plotLGB(skuid)
    plt.savefig(f"D:\\Priceoye\\Inventory_Accuracy_ModelV1\\{skuid}.png")

lgbm_90 = lgb.LGBMRegressor(
    objective = "quantile",
    alpha = 0.90
)

lgbm_90.fit(
    X_train,
    y_train,
    categorical_feature=["sku_id"]
)
pred = lgbm_90.predict(X_test)

mae = mean_absolute_error(y_test, pred)
# print(mae)

importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": lgbm.feature_importances_
}).sort_values("Importance", ascending=False)

# print(importance)

explainer = shap.TreeExplainer(lgbm)
explanation = explainer(X_test)
plt.figure(figsize=(12, 8))

# Pass the single explanation object directly: explanation[0]
shap.waterfall_plot(explanation[0], max_display=15, show=False)

# 3. Explicitly render the plot
plt.title("SHAP Waterfall Plot for Sample Prediction", fontsize=14, pad=15)
plt.tight_layout()
plt.show()

"""#Phase 6

##Safety Stock
"""

#high quantile forecast and demand variability

safety_stock = (
    train_df.groupby('sku_id')['units_sold']
      .quantile(0.90)
      .reset_index()
      .rename(columns={'units_sold': 'q90_daily_demand'})
)

df1 = df.merge(safety_stock, on='sku_id', how='left')
df1["q90_daily_demand"] = df1["q90_daily_demand"].apply(math.ceil)

df1.head()

"""##Stockout or Overstock  """

df1.head()

weekly_df.loc[weekly_df.index.get_level_values("sku_id") == "SKU_APPLE_0189"]

test_df

def checkStock():
  results_df = test_df.copy()

  #Forecast from rolling 8 week mean
  results_df["forecast_demand_8wmean"] = results_df["rolling_8w_mean"]
  # print(results_df)

  # Forecast from LightGBM
  results_df["forecast_demand_LGBM"] = pred
  # print(results_df)
  # Safety stock (already computed previously)
  results_df = results_df.merge(
    df1[["sku_id", "q90_daily_demand"]].drop_duplicates("sku_id"),
    on="sku_id",
    how="left"
).rename(columns={"q90_daily_demand": "safety_stock"})

  # Expected stock after next week's demand
  results_df["expected_stock"] = (
      results_df["recorded_stock"] -
      results_df["forecast_demand_LGBM"]
  )

  # Quantity that should be ordered
  results_df["recommended_order"] = np.maximum(
      0,
      results_df["forecast_demand_LGBM"]
      + results_df["safety_stock"]
      - results_df["recorded_stock"]
  )

  # Inventory status
  conditions = [
      results_df["expected_stock"] < 0,
      results_df["expected_stock"] < results_df["safety_stock"]
  ]

  choices = [
      "Stockout",
      "Low Stock"
  ]

  results_df["status"] = np.select(
      conditions,
      choices,
      default="Safe"
  )
  results_df["overstock_limit"] = (
      results_df["forecast_demand_LGBM"] * 2
      + results_df["safety_stock"]
  )

  results_df.loc[
      results_df["recorded_stock"] > results_df["overstock_limit"],
      "status"
  ] = "Overstock"

  return results_df

finaldf = checkStock()
print(f"{finaldf.columns}")
finaldf.sort_values(by = "expected_stock",ascending=False)

st.set_page_config(
    page_title="Inventory Forecast Dashboard",
    layout="wide"
)

st.title("📦 Inventory Forecast Dashboard")

df = finaldf.copy()

# ---------------- KPIs ---------------- #

c1, c2, c3, c4 = st.columns(4)

c1.metric("Total SKUs", df["sku_id"].nunique())

c2.metric(
    "Stockout",
    (df["status"]=="Stockout").sum()
)

c3.metric(
    "Low Stock",
    (df["status"]=="Low Stock").sum()
)

c4.metric(
    "Overstock",
    (df["status"]=="Overstock").sum()
)

st.divider()

# ---------------- Sidebar ---------------- #

sku = st.sidebar.selectbox(
    "Select SKU",
    sorted(df["sku_id"].unique())
)

sku_df = df[df["sku_id"]==sku].sort_values("date")

# ---------------- Metrics ---------------- #

left, right = st.columns(2)

with left:

    st.subheader("Forecast")

    latest = sku_df.iloc[-1]

    st.metric(
        "Forecast Demand",
        f"{latest['forecast_demand_LGBM']:.0f}"
    )

    st.metric(
        "Current Stock",
        latest["recorded_stock"]
    )

    st.metric(
        "Expected Stock",
        f"{latest['expected_stock']:.0f}"
    )

with right:

    st.subheader("Inventory")

    st.metric(
        "Safety Stock",
        latest["safety_stock"]
    )

    st.metric(
        "Order Quantity",
        f"{latest['recommended_order']:.0f}"
    )

    st.metric(
        "Status",
        latest["status"]
    )

st.divider()

# ---------------- Plot ---------------- #

fig, ax = plt.subplots(figsize=(12,5))

ax.plot(
    sku_df["date"],
    sku_df["units_sold"],
    label="Actual"
)

ax.plot(
    sku_df["date"],
    sku_df["forecast_demand_LGBM"],
    label="Forecast"
)

ax.plot(
    sku_df["date"],
    sku_df["rolling_8w_mean"],
    label="Rolling Mean"
)

ax.legend()

st.pyplot(fig)

st.divider()

st.subheader("SKU Details")

st.dataframe(sku_df)

st.divider()

st.subheader("Complete Inventory Table")

st.dataframe(
    df.sort_values("recommended_order", ascending=False)
)

# %%
